# Generated by Django 2.0.dev20170721222113 on 2017-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='comment',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
